### ISSUE TITLE
Test more than 10 reverse deps

### ISSUE THREAD

**Issue by brson** [brson/cargo-crusader#5]
@DanielKeep [discovered](https://users.rust-lang.org/t/cargo-crusader-0-1-test-the-downstream-impact-of-rust-crate-changes-before-publishing/2373/17?u=brson) that crates.io's revdep API is paginated and only returns 10 results at a time.

**Comment by alexcrichton** [comment]
You can also send a `per_page` url parameter (e.g. `/foo?per_page=10`) of up to 100 if you'd like to get more than 10 per page
