### ISSUE TITLE
Build failure on nightly.

### ISSUE THREAD

**Issue by Sean1708** [brson/cargo-crusader#6]
See [here](https://travis-ci.org/Sean1708/rusty-cheddar/jobs/100006661). I think it should be fixed by bumping the `rustc-serialize` requirement up to `0.3.16`.

**Comment by brson** [comment]
I've updated rustc-serialize, but now rand fails to compile because of [this](https://github.com/rust-lang-nursery/rand/pull/93). There's a fix to Rust that should fix _that_ in tomorrow's nightly.

**Comment by Sean1708** [comment]
Ah perfect, thanks. I'll wait a day or two before trying it out then.
